---
- hosts: qradar
  remote_user: root
  
  tasks:
  - name: Restart hostcontext service
    shell: systemctl restart tomcat
    register: command_result
    
  - name: Return only the shell standard output
    debug: msg="{{ command_result.stdout_lines }}"    
        
...
